# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/addPet_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db.db_conn import dbConnection
from messageBox import messagebox
import json
from PyQt5.QtCore import QObject, pyqtSignal

class Ui_Form(QObject):
    petAdded = pyqtSignal()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(382, 409)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 11, 201, 329))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEditName = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditName.setObjectName("lineEditName")
        self.verticalLayout.addWidget(self.lineEditName)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.spinBoxAge = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxAge.setMinimumSize(QtCore.QSize(48, 26))
        self.spinBoxAge.setMaximumSize(QtCore.QSize(48, 26))
        self.spinBoxAge.setObjectName("spinBoxAge")
        self.verticalLayout.addWidget(self.spinBoxAge)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.dateEditBirth = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEditBirth.setObjectName("dateEditBirth")
        self.verticalLayout.addWidget(self.dateEditBirth)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.dateEditVacination = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEditVacination.setEnabled(True)
        self.dateEditVacination.setObjectName("dateEditVacination")
        self.verticalLayout.addWidget(self.dateEditVacination)
        self.checkBoxVacinated = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBoxVacinated.setObjectName("checkBoxVacinated")
        self.verticalLayout.addWidget(self.checkBoxVacinated)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEditType = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditType.setObjectName("lineEditType")
        self.verticalLayout.addWidget(self.lineEditType)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.buttonBox.rejected.connect(Form.close)
        self.buttonBox.accepted.connect(self.petbox)
        self.dateEditVacination.setVisible(False)
        self.label_5.setVisible(False)
        self.checkBoxVacinated.toggled.connect(self.vacinationShow)
        try:
            with open(".config", "r+t") as f:
                # checking if file is empty
                if f.read().strip():
                    f.seek(0)
                    l = f.readline()
                    l =json.loads(l)
                    self.user_conf = dict(l)
  
                else:
                    raise Exception("File is empty")
        except (Exception,FileNotFoundError) as e:
            messagebox("Crital!", "No config found or it\'s empty!", "Warning")
            raise e

        #print(self.user_conf['id'])
        print(self.dateEditVacination.text())

    def vacinationShow(self):
        if self.checkBoxVacinated.isChecked():
            self.dateEditVacination.setVisible(True)
            self.label_5.setVisible(True)
        else:
            self.dateEditVacination.setVisible(False)
            self.label_5.setVisible(False)

    def petbox(self):
        db = dbConnection()

        age = self.spinBoxAge.value()
        name = str(self.lineEditName.text())
        type_pet = str(self.lineEditType.text())
        birth_date = self.dateEditBirth.text()
        vacination_date = self.dateEditVacination.text()

        if self.checkBoxVacinated.isChecked():
            q = "Insert into animals (name, age, type, user_id, vacination_date, birth_date ) values(%s, %s, %s, %s, %s, %s)"
            params = (name, age, type_pet, int(self.user_conf['id']), vacination_date, birth_date)
        else:
            q = "Insert into animals (name, age, type, user_id, birth_date) values(%s, %s, %s, %s, %s)"
            params = (name, age, type_pet, int(self.user_conf['id']), birth_date)

        db.connect()
        result = db.insert(q, params)
        if result == 1:
            messagebox("Succes", "Pet added", "Information")
            self.petAdded.emit()
        else:
            messagebox("Failure", "Failed to add pet", "Warning")


        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Name"))
        self.label_2.setText(_translate("Form", "Age"))
        self.label_4.setText(_translate("Form", "Birth date"))
        self.label_5.setText(_translate("Form", "Vacination date"))
        self.checkBoxVacinated.setText(_translate("Form", "Vacinated"))
        self.label_3.setText(_translate("Form", "Type"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
