# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets
from db.db_conn import dbConnection
from hashlib import md5
from messageBox import messagebox
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import pyqtSignal, QObject
from psycopg2 import errors

class Ui_Form_register(QObject):
    registerCompleted = pyqtSignal()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(698, 341)
        Form.setMinimumSize(QtCore.QSize(640, 300))
        Form.setMaximumSize(QtCore.QSize(698, 346))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelImage = QtWidgets.QLabel(Form)
        self.labelImage.setMinimumSize(QtCore.QSize(200, 0))
        self.labelImage.setText("")
        self.labelImage.setObjectName("labelImage")
        self.horizontalLayout.addWidget(self.labelImage)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelName = QtWidgets.QLabel(Form)
        self.labelName.setObjectName("labelName")
        self.verticalLayout.addWidget(self.labelName)
        self.lineEditName = QtWidgets.QLineEdit(Form)
        self.lineEditName.setText("")
        self.lineEditName.setObjectName("lineEditName")
        self.verticalLayout.addWidget(self.lineEditName)
        self.labelEmail = QtWidgets.QLabel(Form)
        self.labelEmail.setObjectName("labelEmail")
        self.verticalLayout.addWidget(self.labelEmail)
        self.lineEditEmail = QtWidgets.QLineEdit(Form)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.verticalLayout.addWidget(self.lineEditEmail)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEditPhone = QtWidgets.QLineEdit(Form)
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.verticalLayout.addWidget(self.lineEditPhone)
        self.labelPassword = QtWidgets.QLabel(Form)
        self.labelPassword.setObjectName("labelPassword")
        self.verticalLayout.addWidget(self.labelPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(Form)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.verticalLayout.addWidget(self.lineEditPassword)
        self.labelRetypePassword = QtWidgets.QLabel(Form)
        self.labelRetypePassword.setObjectName("labelRetypePassword")
        self.verticalLayout.addWidget(self.labelRetypePassword)
        self.lineEditRetypePassword = QtWidgets.QLineEdit(Form)
        self.lineEditRetypePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditRetypePassword.setObjectName("lineEditRetypePassword")
        self.verticalLayout.addWidget(self.lineEditRetypePassword)
        self.checkBoxShowPass = QtWidgets.QCheckBox(Form)
        self.checkBoxShowPass.setObjectName("checkBoxShowPass")
        self.verticalLayout.addWidget(self.checkBoxShowPass, 0, QtCore.Qt.AlignLeft)
        self.pushButtonRegister = QtWidgets.QPushButton(Form)
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.verticalLayout.addWidget(self.pushButtonRegister)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButtonRegister.clicked.connect(self.register)
        self.checkBoxShowPass.toggled.connect(self.showpass)

    def showpass(self):
        if self.checkBoxShowPass.isChecked():
            self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Normal)
        else:
            self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)

    def register(self):
        try:
            db = dbConnection()
            db.connect()
            q = """INSERT INTO users(name, password, email, phone) values(%s, %s, %s, %s)"""
            name = self.lineEditName.text()
            phone = self.lineEditPhone.text()
            email = self.lineEditEmail.text()
            password_before = self.lineEditPassword.text()
            password = md5(self.lineEditPassword.text().encode()).hexdigest()
            re_password = md5(self.lineEditRetypePassword.text().encode()).hexdigest()
            #print(name, phone, email)
            if password != re_password:
                messagebox("Password issue", "Passwords don\'t match!", "Warning")
            elif any(char.isdigit() for char in name):
                print(name)
                messagebox("Name issue", "Name can\'t have numbers!", "Warning")
            elif name=="" or phone=="" or email=="" or password_before=="":
                messagebox("Empty inputs", "Please provide all the data", "Warning")
            else:
                params = (name, password, email, phone)
                try:
                    row = db.insert(q, params)
                    if row == 1:
                        messagebox("Success", "Account created", "Information")
                    self.registerCompleted.emit()
                except (Exception, errors.UniqueViolation) as e:
                    messagebox("Failed", "This email or phone already exists!",  "Warning")
        except Exception as e:
            messagebox("ERROR", f"{e}", "Warning")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Register"))
        self.labelName.setText(_translate("Form", "Name"))
        self.labelEmail.setText(_translate("Form", "E-mail"))
        self.label.setText(_translate("Form", "Phone number"))
        self.labelPassword.setText(_translate("Form", "Password"))
        self.labelRetypePassword.setText(_translate("Form", "Retype password"))
        self.checkBoxShowPass.setText(_translate("Form", "Show password"))
        self.pushButtonRegister.setText(_translate("Form", "Register"))

        pixmap = QPixmap("assets/padlock_register.png")
        self.labelImage.setPixmap(pixmap)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form_register()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
